sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login $DOCKER_REGISTRY -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_REGISTRY/fitex/landing:latest .
      - docker images
      - docker push $DOCKER_REGISTRY/fitex/landing:latest
